name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup Git User
        run: |
          git config user.name "waltercoan"
          git config user.email "walter.coan@gmail.com"
      - name: Update Test Branch
        run: |
            git fetch origin
            git checkout -b gh-pages
            git merge --allow-unrelated-histories origin/main
      - run: npm install -g markmap-cli
      - name: Finding files
        id: finding-files        
        run: |
            {
            echo 'FILELIST<<EOF'
            find . -name '*.md' -print 
            echo EOF
            } >> "$GITHUB_ENV"
      - name: Do something with each file
        run: |
            for i in $FILELIST; do
            markmap -o "${i%.*}.html" "${i}"
            done        
      - run: 
      - name: push branch
        run: |
            git add .
            git commit -m "update"
            git push -u origin gh-pages
