name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup Git User
        run: |
          git config user.name "waltercoan"
          git config user.email "walter.coan@gmail.com"
      - name: Update Test Branch
        run: |
            git fetch origin
            git checkout -b gh-pages
            git merge --allow-unrelated-histories origin/main
      - run: npm install -g markmap-cli
      - run: markmap -o ./html/index.html ./mapas/mapa1.md
      - name: Update Test Branch
        run: |
            git add .
            git commit -m "update"
            git branch --set-upstream-to=origin/main gh-pages
